#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

PATH="$HOME/.config/bspwm/scripts:$PATH"

bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          12

# Border colors
bspc config normal_border_color "#6c7086"
bspc config focused_border_color "#89b4fa"
bspc config urgent_border_color "#f38ba8"
bspc config presel_border_color "#f2cdcd"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
~/.config/bspwm/autostart.sh
